version: "3.9"
services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - FIRESTORE_PROJECT_ID=${FIRESTORE_PROJECT_ID}
      - FIRESTORE_PORT=$FIRESTORE_PORT
      - FIRESTORE_EMULATOR_HOST=${FIRESTORE_EMULATOR_HOST}
      - PORT=${PORT}
      - USERS_SERVICE_BASE_URL=${USERS_SERVICE_BASE_URL}
    depends_on:
      firestore_emulator: 
        condition: 
          service_healthy
  firestore_emulator:
    image: mtlynch/firestore-emulator
    ports:
      - "${FIRESTORE_PORT}:${FIRESTORE_PORT}"
    environment:
      - FIRESTORE_PROJECT_ID=${FIRESTORE_PROJECT_ID}
      - PORT=${FIRESTORE_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FIRESTORE_PORT}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
