name: 'Build and test'

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.GCP_DEV_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_DEV_SA_EMAIL }}
      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - uses: actions/setup-go@v3
      - name: Test
        run: ./test.sh
